# Generated by Django 4.2.7 on 2023-11-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
    ]
