# Generated by Django 3.2.22 on 2023-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookatable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='capacity',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12')], default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[(1, '10:00 - 10:45'), (2, '11:00 - 11:45'), (3, '12:00 - 12:45'), (4, '13:00 - 13:45'), (5, '14:00 - 14:45'), (6, '15:00 - 15:45'), (7, '16:00 - 16:45'), (8, '17:00 - 17:45'), (8, '18:00 - 18:45'), (8, '19:00 - 19:45'), (8, '20:00 - 20:45'), (8, '21:00 - 21:45'), (8, '22:00 - 22:45')], default='10:00 - 10:45', max_length=5),
        ),
    ]
