# Generated by Django 3.2.22 on 2023-11-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookatable', '0002_auto_20231114_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='capacity',
        ),
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (5, '4'), (4, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=2),
        ),
    ]
