# Generated by Django 3.2.22 on 2023-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookatable', '0003_auto_20231114_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('1', '10:00 - 10:45'), ('2', '11:00 - 11:45'), ('3', '12:00 - 12:45'), ('4', '13:00 - 13:45'), ('5', '14:00 - 14:45'), ('6', '15:00 - 15:45'), ('7', '16:00 - 16:45'), ('8', '17:00 - 17:45'), ('9', '18:00 - 18:45'), ('10', '19:00 - 19:45'), ('11', '20:00 - 20:45'), ('12', '21:00 - 21:45'), ('13', '22:00 - 22:45')], default='10:00 - 10:45', max_length=20),
        ),
    ]
