# Generated by Django 4.2.7 on 2023-11-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookatable', '0004_alter_booking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_tables',
        ),
    ]
