# Generated by Django 4.2.7 on 2023-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookatable', '0006_alter_booking_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('10:00', '10:00 - 10:45'), ('11:00', '11:00 - 11:45'), ('12:00', '12:00 - 12:45'), ('13:00', '13:00 - 13:45'), ('14:00', '14:00 - 14:45'), ('15:00', '15:00 - 15:45'), ('16:00', '16:00 - 16:45'), ('17:00', '17:00 - 17:45'), ('18:00', '18:00 - 18:45'), ('19:00', '19:00 - 19:45'), ('20:00', '20:00 - 20:45'), ('21:00', '21:00 - 21:45'), ('22:00', '22:00 - 22:45')], default='10:00 - 10:45', max_length=20),
        ),
    ]
